import '@fontsource/kanit/thai-400.css';
import '@fontsource/kanit/thai-500.css';
import '@fontsource/kanit/thai-600.css';
import '@fontsource/kanit/thai-700.css';
import '@fontsource/kanit/thai-800.css';
import '@fontsource/plus-jakarta-sans/latin-400.css';
import '@fontsource/plus-jakarta-sans/latin-600.css';
import '@fontsource/plus-jakarta-sans/latin-700.css';
import '@fontsource/jetbrains-mono/latin-500.css';
import '@fontsource/jetbrains-mono/latin-600.css';
import '@fontsource/jetbrains-mono/latin-700.css';
import '@fontsource/noto-sans-thai/thai-400.css';
import '@fontsource/noto-sans-thai/thai-500.css';
import '@fontsource/noto-sans-thai/thai-600.css';
import '@fontsource/noto-sans-thai/thai-700.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
import '@fontsource/ibm-plex-mono/400.css';
import '@fontsource/ibm-plex-mono/500.css';
import '@fontsource/ibm-plex-mono/600.css';
import '../../src/styles.css';
import '../../src/design-system.css';
import '../../src/styles/dashboard.css';
import '../../src/styles/license-table.css';
import '../../src/styles/responsive-shell.css';
import '../../src/styles/action-system.css';
import '../../src/styles/tokens.css';
import '../../src/styles/theme-foundation.css';
import '../../src/styles/app-shell.css';
import '../../src/styles/data-surfaces.css';
import '../../src/styles/auth-experience.css';
import '../../src/styles/visual-fidelity.css';
import '../../src/styles/signature-experience.css';
import '../../src/styles/signature-experience-v1-1.css';
import '../../src/styles/signature-experience-v1-2.css';
import '../../src/styles/production-mobile-responsive-v1.css';
import '../../src/styles/attendance-device.css';
import '../../src/styles/pwa-shell.css';
import '../../src/styles/responsive-certification-v1.css';
import '../../src/styles/system-health.css';
import '../../src/styles/configuration-center.css';
import '../../src/styles/ux-ui-remediation.css';
import '../../src/styles/ux-ui-quality-10.css';
import '../../src/styles/award-landing.css';
import '../../src/styles/tailwind.css';
import '../../src/styles/command-nexus.css';
import '../../src/styles/award-interior.css';
import '../../src/styles/operational-layer.css';
import '../../src/styles/employee-pwa-theme.css';
import '../../src/styles/ux-t06-login-public.css';
import '../../src/styles/schedule-roster-ux.css';
import '../../src/styles/layout-foundation.css';

import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {PageHeader, SectionCard, StepFlow, MetricCard} from '../../src/components/layout';
import {ThemeControl} from '../../src/components/ThemeControl';
function Fixture(){const [opened,setOpened]=useState(0);return <main className="app-shell"><div className="content-area"><div className="view-pane"><PageHeader kicker="ข้อมูลปฏิบัติการ" title="รายการของหน่วยงาน" description="ตรวจข้อมูลตามสิทธิ์ก่อนทำงาน" actions={<ThemeControl />} /><SectionCard kicker="ข้อมูลที่ตรวจสอบแล้ว" title="รายการสำคัญ" description="การ์ดหลักตามแบบที่อนุมัติ"><p>ข้อมูลทดสอบสำหรับตรวจรูปลักษณ์เท่านั้น</p><div className="table-scroll"><table><caption>รายการทดสอบ</caption><tbody><tr><th scope="row">จำนวนรายการ</th><td>{opened}</td></tr></tbody></table></div></SectionCard><MetricCard label="รายการรออนุมัติ" value={12} description="ตัวอย่างข้อมูลสังเคราะห์" icon="approval" /><StepFlow description="เลือกขั้นตอนที่พร้อม" steps={[{id:'month',icon:'calendar',label:'ขั้นที่หนึ่ง',title:'เลือกเดือน',desc:'เลือกเดือนที่ต้องการ',current:true,onClick:()=>setOpened(n=>n+1)},{id:'review',icon:'approval',label:'ขั้นที่สอง',title:'ตรวจข้อมูล',desc:'ข้อมูลผ่านการตรวจแล้ว',completed:true}]} /><output aria-label="จำนวนการเปิดรายการ">{opened}</output></div></div></main>}
createRoot(document.getElementById('root')!).render(<Fixture />);
