'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const svc=require('../src/services/system-setting-history.service');

test('CFG-11 restore eligibility is limited to registered editable non-secret settings',()=>{assert.equal(svc.eligible('LINE_TEMPLATE_NEW_LEAVE'),true);assert.equal(svc.eligible('JWT_SECRET'),false);assert.equal(svc.eligible('UNREGISTERED_KEY'),false);});

test('CFG-11 history presents before/after and marks legacy entries non-restorable when value missing',async()=>{const prisma={auditLog:{findMany:async()=>[{id:'1',entityId:'LINE_TEMPLATE_NEW_LEAVE',action:'UPDATE',createdAt:new Date('2026-09-01T00:00:00Z'),actor:{id:'u',displayName:'Admin',email:'a@example.test'},metadata:{beforeValue:'A',afterValue:'B',reason:'change'}},{id:'2',entityId:'LINE_TEMPLATE_NEW_LEAVE',action:'UPDATE',createdAt:new Date('2026-08-01T00:00:00Z'),actor:null,metadata:{valueChanged:true}}]}};const out=await svc.history(prisma,'LINE_TEMPLATE_NEW_LEAVE');assert.equal(out.history[0].beforeValue,'A');assert.equal(out.history[0].afterValue,'B');assert.equal(out.history[0].restorable,true);assert.equal(out.history[1].restorable,false);});

test('CFG-11 restore creates a new audited change and never rewrites history',async()=>{let auditPayload;const source={id:'11111111-1111-4111-8111-111111111111',entityType:'SystemSetting',entityId:'LINE_TEMPLATE_NEW_LEAVE',metadata:{afterValue:'Historical template'}};const tx={systemSetting:{findUnique:async()=>({key:'LINE_TEMPLATE_NEW_LEAVE',value:'Current template'}),upsert:async({update})=>({key:'LINE_TEMPLATE_NEW_LEAVE',value:update.value,description:'x',updatedAt:new Date()})}};const prisma={auditLog:{findFirst:async()=>source},$transaction:async fn=>fn(tx)};const audit={log:async p=>{auditPayload=p;}};const out=await svc.restore({prisma,audit,actor:{sub:'admin'},key:'LINE_TEMPLATE_NEW_LEAVE',auditLogId:source.id,reason:'Restore approved prior template'});assert.equal(out.value,'Historical template');assert.equal(auditPayload.metadata.event,'SYSTEM_SETTING_RESTORED');assert.equal(auditPayload.metadata.beforeValue,'Current template');assert.equal(auditPayload.metadata.afterValue,'Historical template');assert.equal(auditPayload.metadata.reason,'Restore approved prior template');});
