'use strict';
const fs=require('node:fs'); const path=require('node:path'); const test=require('node:test'); const assert=require('node:assert/strict');
const { validateMdg01bSql, validateMigrationManifest }=require('../scripts/ci/verify-approved-production-migration');
const root=path.join(__dirname,'..'); const manifest=JSON.parse(fs.readFileSync(path.join(root,'.github/releases/approved-mdg-01b-production-migration.json'),'utf8')); const sql=fs.readFileSync(path.join(root,...manifest.migration_path.split('/')),'utf8'); const workflow=fs.readFileSync(path.join(root,'.github/workflows/apply-approved-mdg-01b-production-migration.yml'),'utf8').replace(/\r\n/g,'\n'); const post=fs.readFileSync(path.join(root,'scripts/ci/verify-mdg-01b-production-migration.js'),'utf8');
test('MDG-01B Production migration manifest is exact-source pinned and migration-only',()=>{ const r=validateMigrationManifest(manifest,{root}); assert.equal(r.migrationId,'MDG-01B'); assert.equal(r.sourceCommitSha,'aa7a79c43e4f3ece40017ce61dbcfee8684e2a83'); assert.equal(r.sourceTreeSha,'74e9146e33451aac304bd36eff1c5aecb9006033'); assert.equal(r.currentProductionDeploymentId,'dpl_Bmp7d7QUFHrXKFcoUj3RUau2skyN'); assert.equal(r.currentProductionApplicationSha,'d1d171c8d3f9ddf744e170d0a2be290ac2663a04'); assert.equal(r.dataBackfill,true); assert.equal(r.controlledUpdateCount,3); assert.equal(manifest.application_deploy,false); });
test('MDG-01B SQL guard permits exact additive authority migration and rejects unrelated mutation',()=>{ assert.doesNotThrow(()=>validateMdg01bSql(sql)); for(const unsafe of [sql+'\nDROP TABLE employees;',sql+'\nUPDATE employees SET department=\'x\';',sql+'\nDELETE FROM employees;',sql+'\nALTER TABLE employees ADD COLUMN unsafe TEXT;',sql+'\nINSERT INTO employees (id) VALUES (gen_random_uuid());']) assert.throws(()=>validateMdg01bSql(unsafe),/forbidden|requires exactly|mismatch|unexpected/i); });
test('MDG-01B workflow is dispatch-only with one Production environment gate and no app deploy',()=>{ assert.match(workflow,/name: Apply Approved MDG-01B Production Migration/); assert.match(workflow,/on:\n  workflow_dispatch:/); assert.doesNotMatch(workflow,/\n  push:/); assert.match(workflow,/MANIFEST_PATH: \.github\/releases\/approved-mdg-01b-production-migration\.json/); assert.match(workflow,/name: Approve Production Migration/); assert.match(workflow,/environment:\n\s+name: production-sms-v3-staging/); assert.match(workflow,/node scripts\/ci\/prisma-migration\.js deploy/); assert.doesNotMatch(workflow,/vercel(?:@[^\s]+)?\s+(?:deploy|promote|rollback)/i); });
test('MDG-01B post verifier checks stable codes, FK authority and compatibility without raw values',()=>{ assert.match(post,/MDG_01B_PRODUCTION_MIGRATION_VERIFY=PASS/); assert.match(post,/MASTER_CODE_COVERAGE=PASS/); assert.match(post,/DEPARTMENT_SITE_AUTHORITY_COVERAGE=PASS/); assert.match(post,/LEGACY_DEPARTMENT_SNAPSHOT_COMPATIBILITY=PASS/); assert.match(post,/RAW_PERSONNEL_VALUES_EMITTED=false/); });

test('MDG-01B dispatch alias uses a GitHub-registered workflow path without weakening controls',()=>{ const alias=fs.readFileSync(path.join(root,'.github/workflows/one-time-vercel-production-sync.yml'),'utf8').replace(/\r\n/g,'\n'); assert.match(alias,/name: Apply Approved MDG-01B Production Migration/); assert.match(alias,/on:\n  workflow_dispatch:/); assert.doesNotMatch(alias,/\n  push:/); assert.match(alias,/MANIFEST_PATH: \.github\/releases\/approved-mdg-01b-production-migration\.json/); assert.match(alias,/name: Approve Production Migration/); assert.match(alias,/node scripts\/ci\/prisma-migration\.js deploy/); assert.doesNotMatch(alias,/vercel(?:@[^\s]+)?\s+(?:deploy|promote|rollback)/i); });
