'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { createOnboardingReadinessService } = require('../src/services/onboarding-readiness.service');

function baseEmployee(overrides = {}) { return { id: 'employee-1', isActive: true, department: 'Operations', jobTitle: 'Officer', user: { id: 'user-1', role: 'EMPLOYEE', isActive: true, accountStatus: 'ACTIVE' }, referencePhotos: [{ id: 'photo-1' }], attendanceDevices: [{ id: 'device-1', status: 'ACTIVE', proofVerifiedAt: new Date('2026-08-31T00:00:00Z') }], ...overrides }; }
function harness({ employee = baseEmployee(), assignment = { id: 'assignment-1', employeeId: 'employee-1', workDate: new Date('2026-09-02T00:00:00Z'), shiftType: { code: 'DAY', name: 'Day' }, securitySite: null }, approval = { status: 'APPROVED' }, site = { site: { id: 'site-1', code: 'HQ', name: 'HQ' }, source: 'DEPARTMENT_DEFAULT' } } = {}) { const prisma = { employee: { findFirst: async () => employee }, shiftAssignment: { findFirst: async () => assignment }, scheduleApproval: { findFirst: async () => approval } }; const siteAuthorityService = { resolve: async () => site }; return createOnboardingReadinessService({ prisma, siteAuthorityService, clock: () => new Date('2026-09-01T10:00:00Z') }); }

test('READY requires every authoritative onboarding prerequisite', async () => { const result = await harness().getEmployeeReadiness({ employeeId: 'employee-1' }); assert.equal(result.status, 'READY'); assert.equal(result.blockers.length, 0); assert.equal(result.checks.device.ready, true); assert.equal(result.checks.site.source, 'DEPARTMENT_DEFAULT'); });
test('missing account, photo, schedule and device remain explicit blockers', async () => { const service = harness({ employee: baseEmployee({ user: null, referencePhotos: [], attendanceDevices: [] }), assignment: null, approval: null, site: null }); const result = await service.getEmployeeReadiness({ employeeId: 'employee-1' }); assert.equal(result.status, 'NOT_READY'); assert.deepEqual(new Set(result.blockers.map((x) => x.code)), new Set(['ACCOUNT_REQUIRED','REFERENCE_PHOTO_REQUIRED','SCHEDULE_REQUIRED','ATTENDANCE_DEVICE_REQUIRED'])); });
test('unapproved schedule and unresolved site fail closed', async () => { const service = harness({ approval: { status: 'PENDING' }, site: null }); service.getEmployeeReadiness; const result = await service.getEmployeeReadiness({ employeeId: 'employee-1' }); assert.equal(result.status, 'NOT_READY'); assert.ok(result.blockers.some((x) => x.code === 'SCHEDULE_NOT_APPROVED')); assert.ok(result.blockers.some((x) => x.code === 'SITE_REQUIRED')); });
test('multiple active devices are an authority conflict, never READY', async () => { const employee = baseEmployee({ attendanceDevices: [{ id: 'd1', proofVerifiedAt: new Date() }, { id: 'd2', proofVerifiedAt: new Date() }] }); const result = await harness({ employee }).getEmployeeReadiness({ employeeId: 'employee-1' }); assert.equal(result.status, 'NOT_READY'); assert.equal(result.checks.device.activeCount, 2); });
