const express = require('express');
const authRoutes = require('./auth.routes');
const usersRoutes = require('./users.routes');
const employeesRoutes = require('./employees.routes');
const shiftsRoutes = require('./shifts.routes');
const schedulesRoutes = require('./schedules.routes');
const operationsRoutes = require('./operations.routes');
const dataQualityRoutes = require('./data-quality.routes');
const registrationRequestRoutes = require('./registration-requests.routes');
const employeeChangeRequestRoutes = require('./employee-change-requests.routes');
const attendanceDeviceRoutes = require('./attendance-device.routes');
const employeeReferencePhotoRoutes = require('./employee-reference-photo.routes');

const router = express.Router();
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/employees', employeesRoutes);
router.use('/registration-requests', registrationRequestRoutes);
router.use('/employee-change-requests', employeeChangeRequestRoutes);
router.use('/attendance/devices', attendanceDeviceRoutes);
router.use('/employee-reference-photos', employeeReferencePhotoRoutes);
router.use('/shift-types', shiftsRoutes);
router.use('/schedules', schedulesRoutes);
router.use('/schedule-calendar', schedulesRoutes);
router.use('/data-quality', dataQualityRoutes);
router.use('/', operationsRoutes);
module.exports = router;
