const express = require('express');
const authRoutes = require('./auth.routes');
const usersRoutes = require('./users.routes');
const employeesRoutes = require('./employees.routes');
const shiftsRoutes = require('./shifts.routes');
const schedulesRoutes = require('./schedules.routes');
const operationsRoutes = require('./operations.routes');
const dataQualityRoutes = require('./data-quality.routes');
const registrationRequestRoutes = require('./registration-requests.routes');
const employeeChangeRequestRoutes = require('./employee-change-requests.routes');
const attendanceDeviceRoutes = require('./attendance-device.routes');
const { router: attendanceRoutes } = require('./attendance.routes');
const { router: attendanceSupervisorRoutes } = require('./attendance-supervisor.routes');
const { router: attendanceAdjustmentRoutes } = require('./attendance-adjustment.routes');
const { router: attendanceGovernanceRoutes } = require('./attendance-governance.routes');
const employeeReferencePhotoRoutes = require('./employee-reference-photo.routes');
const approvalCenterRoutes = require('./approval-center.routes');
const { router: faceVerificationRoutes } = require('./face-verification.routes');
const { router: selfHostedFaceVerificationRoutes } = require('./face-verification-self-hosted.routes');
const securitySitesRoutes = require('./security-sites.routes');
const personnelMastersRoutes = require('./personnel-masters.routes');
const systemHealthRoutes = require('./system-health.routes');

const router = express.Router();
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/employees', employeesRoutes);
router.use('/registration-requests', registrationRequestRoutes);
router.use('/employee-change-requests', employeeChangeRequestRoutes);
router.use('/attendance/devices', attendanceDeviceRoutes);
router.use('/attendance/supervisor', attendanceSupervisorRoutes);
router.use('/attendance/adjustment-requests', attendanceAdjustmentRoutes);
router.use('/attendance/governance', attendanceGovernanceRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/employee-reference-photos', employeeReferencePhotoRoutes);
router.use('/approval-center', approvalCenterRoutes);
router.use('/face-verification', faceVerificationRoutes);
router.use('/face-verification-self-hosted', selfHostedFaceVerificationRoutes);
router.use('/admin/security-sites', securitySitesRoutes);
router.use('/personnel-masters', personnelMastersRoutes);
router.use('/admin/system-health', systemHealthRoutes);
router.use('/shift-types', shiftsRoutes);
router.use('/schedules', schedulesRoutes);
router.use('/schedule-calendar', schedulesRoutes);
router.use('/data-quality', dataQualityRoutes);
router.use('/', operationsRoutes);
module.exports = router;
