const { ATTENDANCE_POLICY_KEYS, DEFAULT_ATTENDANCE_POLICY, policyFromSettings } = require('./attendance-policy.service');

const HIGH_IMPACT_ATTENDANCE_KEYS = new Set(Object.values(ATTENDANCE_POLICY_KEYS));
const BLOCKED_WEB_CONFIGURATION_PATTERNS = Object.freeze([/SECRET/i,/TOKEN/i,/PASSWORD/i,/CREDENTIAL/i,/DATABASE/i,/JWT/i,/SUPABASE/i,/SMTP/i,/VERCEL/i,/MIGRATION/i,/DEPLOY/i,/ROLLBACK/i,/FACE.*(ENABLED|REQUIRED|MODE|PROVIDER)/i,/DEVICE.*(ENABLED|REQUIRED|BIND)/i,/ANTI.?REPLAY/i,/SERVER.?TIME/i]);

function isBlockedWebConfigurationKey(key){return BLOCKED_WEB_CONFIGURATION_PATTERNS.some((pattern)=>pattern.test(String(key||'')));}
function isHighImpactSetting(key){return HIGH_IMPACT_ATTENDANCE_KEYS.has(String(key||''));}
function guardrailMetadata(key){return isHighImpactSetting(key)?{riskLevel:'HIGH',confirmationRequired:true,reasonRequired:true,guardrail:'ATTENDANCE_SECURITY_POLICY'}:{riskLevel:'STANDARD',confirmationRequired:false,reasonRequired:false,guardrail:null};}
function assertAttendanceCombination(rows){const policy=policyFromSettings(rows);const violations=[];if(policy.autoPassAccuracyMeters>policy.maxAccuracyMeters)violations.push('Auto-pass GPS accuracy cannot exceed maximum accepted GPS accuracy.');if(policy.qrPolicy==='DISABLED'&&!policy.stepUpOnSiteOverlap)violations.push('QR cannot be disabled while site-overlap step-up is also disabled.');if(policy.qrPolicy==='ADAPTIVE'&&!policy.stepUpOnSiteOverlap)violations.push('Adaptive QR requires site-overlap step-up to remain enabled.');if(policy.maxAgeMs>300000)violations.push('GPS sample age above 300 seconds is not allowed for governed Attendance.');if(policy.futureSkewMs>60000)violations.push('GPS future skew above 60 seconds is not allowed for governed Attendance.');if(violations.length){const error=new Error(violations.join(' '));error.code='UNSAFE_ATTENDANCE_CONFIGURATION';error.violations=violations;throw error;}return policy;}
async function assertSystemSettingChangeSafe(client,key,value){if(isBlockedWebConfigurationKey(key)){const error=new Error('This security/release setting is outside normal web configuration.');error.code='PROTECTED_SETTING_WEB_CONFIGURATION_DENIED';throw error;}if(!isHighImpactSetting(key))return;const keys=Object.values(ATTENDANCE_POLICY_KEYS);const rows=await client.systemSetting.findMany({where:{key:{in:keys}},select:{key:true,value:true}});const proposed=rows.filter((row)=>row.key!==key).concat({key,value});assertAttendanceCombination(proposed);}
module.exports={HIGH_IMPACT_ATTENDANCE_KEYS,BLOCKED_WEB_CONFIGURATION_PATTERNS,isBlockedWebConfigurationKey,isHighImpactSetting,guardrailMetadata,assertAttendanceCombination,assertSystemSettingChangeSafe};
