'use strict';
const HttpError=require('../utils/http-error');
const {getSystemSettingDefinition,isSensitiveSystemSettingKey,normalizeRegisteredSystemSettingValue,presentRegisteredSystemSetting}=require('./system-setting-registry.service');
const {isReservedOperationalSettingKey}=require('./g03-1-multi-year-activation.service');
function eligible(key){const d=getSystemSettingDefinition(key);return Boolean(d?.editable)&&!isSensitiveSystemSettingKey(key)&&!isReservedOperationalSettingKey(key);}
function present(row){const m=row.metadata&&typeof row.metadata==='object'?row.metadata:{};return {id:row.id,key:row.entityId,action:row.action,createdAt:row.createdAt,actor:row.actor?{id:row.actor.id,displayName:row.actor.displayName,email:row.actor.email}:null,beforeValue:Object.prototype.hasOwnProperty.call(m,'beforeValue')?m.beforeValue:null,afterValue:Object.prototype.hasOwnProperty.call(m,'afterValue')?m.afterValue:null,reason:m.reason||null,event:m.event||null,restorable:Boolean(m.afterValue!==undefined&&eligible(row.entityId))};}
async function history(prisma,key){const d=getSystemSettingDefinition(key);if(!d)throw new HttpError(404,'System setting is not registered.',{code:'SYSTEM_SETTING_NOT_REGISTERED'});const rows=await prisma.auditLog.findMany({where:{entityType:'SystemSetting',entityId:key},orderBy:{createdAt:'desc'},take:100,include:{actor:{select:{id:true,displayName:true,email:true}}}});return {key,label:d.label,restorable:eligible(key),history:rows.map(present)};}
async function restore({prisma,audit,actor,key,auditLogId,reason}){if(!eligible(key))throw new HttpError(403,'This setting is not eligible for restore.',{code:'SYSTEM_SETTING_RESTORE_NOT_ALLOWED'});const source=await prisma.auditLog.findFirst({where:{id:auditLogId,entityType:'SystemSetting',entityId:key}});const metadata=source?.metadata&&typeof source.metadata==='object'?source.metadata:{};if(!source||metadata.afterValue===undefined)throw new HttpError(409,'Selected history entry does not contain a restorable value.',{code:'SYSTEM_SETTING_HISTORY_NOT_RESTORABLE'});let normalized;try{normalized=normalizeRegisteredSystemSettingValue(key,String(metadata.afterValue));}catch(error){throw new HttpError(409,'Historical value no longer passes current validation.',{code:'SYSTEM_SETTING_HISTORY_VALUE_INVALID'});}return prisma.$transaction(async tx=>{const before=await tx.systemSetting.findUnique({where:{key}});const after=await tx.systemSetting.upsert({where:{key},update:{value:normalized},create:{key,value:normalized,description:getSystemSettingDefinition(key).description}});await audit.log({actorUserId:actor.sub,action:before?'UPDATE':'CREATE',entityType:'SystemSetting',entityId:key,metadata:{event:'SYSTEM_SETTING_RESTORED',sourceAuditLogId:auditLogId,beforeValue:before?.value??null,afterValue:after.value,reason}},tx);return presentRegisteredSystemSetting(after);});}
module.exports={eligible,history,restore};
