import '@fontsource/kanit/thai-400.css';
import '@fontsource/kanit/thai-500.css';
import '@fontsource/kanit/thai-600.css';
import '@fontsource/kanit/thai-700.css';
import '@fontsource/kanit/thai-800.css';
import '@fontsource/plus-jakarta-sans/latin-400.css';
import '@fontsource/plus-jakarta-sans/latin-600.css';
import '@fontsource/plus-jakarta-sans/latin-700.css';
import '@fontsource/jetbrains-mono/latin-500.css';
import '@fontsource/jetbrains-mono/latin-600.css';
import '@fontsource/jetbrains-mono/latin-700.css';
import '@fontsource/noto-sans-thai/thai-400.css';
import '@fontsource/noto-sans-thai/thai-500.css';
import '@fontsource/noto-sans-thai/thai-600.css';
import '@fontsource/noto-sans-thai/thai-700.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
import '@fontsource/ibm-plex-mono/400.css';
import '@fontsource/ibm-plex-mono/500.css';
import '@fontsource/ibm-plex-mono/600.css';
import '../../src/styles.css';
import '../../src/design-system.css';
import '../../src/styles/dashboard.css';
import '../../src/styles/license-table.css';
import '../../src/styles/responsive-shell.css';
import '../../src/styles/action-system.css';
import '../../src/styles/tokens.css';
import '../../src/styles/theme-foundation.css';
import '../../src/styles/app-shell.css';
import '../../src/styles/data-surfaces.css';
import '../../src/styles/auth-experience.css';
import '../../src/styles/visual-fidelity.css';
import '../../src/styles/signature-experience.css';
import '../../src/styles/signature-experience-v1-1.css';
import '../../src/styles/signature-experience-v1-2.css';
import '../../src/styles/production-mobile-responsive-v1.css';
import '../../src/styles/attendance-device.css';
import '../../src/styles/pwa-shell.css';
import '../../src/styles/responsive-certification-v1.css';
import '../../src/styles/system-health.css';
import '../../src/styles/configuration-center.css';
import '../../src/styles/ux-ui-remediation.css';
import '../../src/styles/ux-ui-quality-10.css';
import '../../src/styles/award-landing.css';
import '../../src/styles/tailwind.css';
import '../../src/styles/command-nexus.css';
import '../../src/styles/award-interior.css';
import '../../src/styles/operational-layer.css';
import '../../src/styles/employee-pwa-theme.css';
import '../../src/styles/ux-t06-login-public.css';
import '../../src/styles/schedule-roster-ux.css';
import '../../src/styles/layout-foundation.css';

import React from 'react';
import {createRoot} from 'react-dom/client';
import {AppLoader} from '../../src/components/AppLoader';
import {applyThemePreference} from '../../src/theme';
const query = new URLSearchParams(location.search);
applyThemePreference(query.get('theme') === 'dark' ? 'dark' : 'light', document.documentElement);
if(query.get('employee') === '1') document.documentElement.dataset.smsShell = 'employee';
createRoot(document.getElementById('root')!).render(<AppLoader variant={query.get('variant') === 'content' ? 'content' : 'fullscreen'} message="กำลังเตรียมระบบ…" />);
