import { useEffect, useMemo, useState } from 'react';
import { api } from '../../api';

type Row={employee:{id:string;employeeCode:string;firstName:string;lastName:string;department?:string|null;jobTitle?:string|null};status:'READY'|'NOT_READY';blockers:Array<{code:string;label:string;detail:string}>;checks:Record<string,{ready:boolean;[key:string]:unknown}>};
type Response={data:Row[];summary:{total:number;ready:number;notReady:number;blockerCounts:Record<string,number>};limitedTo:number};
export function AttendanceReadinessCenter({token}:{token?:string}){
 const [data,setData]=useState<Response>();const [loading,setLoading]=useState(false);const [error,setError]=useState(false);const [filter,setFilter]=useState<'ALL'|'READY'|'NOT_READY'>('ALL');
 useEffect(()=>{if(!token){setData(undefined);return;}let active=true;setLoading(true);setError(false);api.employeeReadinessCenter(token,'',50).then((result)=>{if(active)setData(result as Response);}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[token]);
 const rows=useMemo(()=>!data?[]:filter==='ALL'?data.data:data.data.filter((row)=>row.status===filter),[data,filter]);
 return <section className="attendance-readiness-center" aria-labelledby="attendance-readiness-center-title"><div className="attendance-readiness-center__heading"><div><p className="eyebrow">Attendance Readiness</p><h2 id="attendance-readiness-center-title">ความพร้อมก่อนเริ่มลงเวลา</h2><p>สถานะทั้งหมดมาจาก server authority; client มีหน้าที่แสดงผลเท่านั้น</p></div>{data&&<div className="attendance-readiness-center__metrics"><span><b>{data.summary.ready}</b> READY</span><span><b>{data.summary.notReady}</b> NOT READY</span><span><b>{data.summary.total}</b> ตรวจแล้ว</span></div>}</div>
 {loading?<div className="personnel-loading" role="status">กำลังตรวจความพร้อม…</div>:error?<div className="personnel-360-data-note" role="status">ไม่สามารถอ่าน Attendance readiness authority ได้ จึงไม่สรุปสถานะ</div>:data?<><div className="attendance-readiness-center__filters" role="group" aria-label="กรองความพร้อม"><button type="button" className={filter==='ALL'?'is-active':''} onClick={()=>setFilter('ALL')}>ทั้งหมด</button><button type="button" className={filter==='READY'?'is-active':''} onClick={()=>setFilter('READY')}>READY</button><button type="button" className={filter==='NOT_READY'?'is-active':''} onClick={()=>setFilter('NOT_READY')}>NOT READY</button></div><div className="attendance-readiness-center__list">{rows.map((row)=><article key={row.employee.id} className="attendance-readiness-row"><div><strong>{row.employee.firstName} {row.employee.lastName}</strong><small>{row.employee.employeeCode} · {row.employee.department||'ไม่ระบุ Department'} · {row.employee.jobTitle||'ไม่ระบุ Position'}</small></div><span className={row.status==='READY'?'status-badge status-badge--success':'status-badge status-badge--warning'}>{row.status}</span><p>{row.status==='READY'?'ผ่าน prerequisite ที่บังคับทั้งหมด':row.blockers.map((item)=>item.label).join(' · ')}</p></article>)}</div>{data.summary.total===data.limitedTo&&<small className="attendance-readiness-center__limit">แสดงสูงสุด {data.limitedTo} รายการต่อการตรวจหนึ่งครั้ง</small>}</>:null}</section>;
}
