import { useEffect, useRef, useState } from 'react';
import type { PersonnelRecord, PersonnelRole } from './types';
type Props = { employee?: PersonnelRecord; canManage: boolean; role: PersonnelRole; onClose(): void; onEdit(): void };
export function PersonnelDetailDrawer({ employee, canManage, onClose, onEdit }: Props) {
  const closeRef = useRef<HTMLButtonElement>(null); const drawerRef = useRef<HTMLElement>(null); const [tab, setTab] = useState('overview');
  useEffect(() => { if (!employee) return; setTab('overview'); closeRef.current?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') { onClose(); return; } if (event.key !== 'Tab' || !drawerRef.current) return; const focusable = Array.from(drawerRef.current.querySelectorAll<HTMLElement>('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')).filter((element) => !element.hasAttribute('disabled')); if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [employee, onClose]);
  if (!employee) return null;
  const fullName = `${employee.firstName} ${employee.lastName}`.trim();
  const tabs = [['overview', 'ภาพรวม'], ['employment', 'การทำงาน'], ['organization', 'หน่วยงาน'], ['access', 'สิทธิ์และบทบาท'], ['audit', 'ประวัติการตรวจสอบ']];
  return <div className="personnel-drawer-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside ref={drawerRef} className="personnel-detail-drawer" role="dialog" aria-modal="true" aria-labelledby="personnel-drawer-title"><header className="personnel-drawer-header"><div className="personnel-drawer-identity"><span className="personnel-drawer-avatar" aria-hidden="true">{fullName.split(/\s+/).map((value) => value[0]).join('').slice(0, 2) || 'SM'}</span><div><p>PERSONNEL PROFILE</p><h2 id="personnel-drawer-title">{fullName || 'พนักงาน'}</h2><span>{employee.employeeCode}</span></div></div><button ref={closeRef} type="button" className="personnel-drawer-close" aria-label="ปิดรายละเอียดพนักงาน" onClick={onClose}>×</button></header><div className="personnel-drawer-tabs" role="tablist">{tabs.map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}</button>)}</div><section className="personnel-drawer-content"><h3>{tabs.find(([value]) => value === tab)?.[1]}</h3>{tab === 'overview' && <dl className="personnel-detail-grid"><div><dt>รหัสพนักงาน</dt><dd>{employee.employeeCode}</dd></div><div><dt>สถานะ</dt><dd>{employee.isActive ? 'ใช้งาน' : 'ไม่ใช้งาน'}</dd></div><div><dt>หน่วยงาน</dt><dd>{employee.department || 'ไม่ระบุ'}</dd></div><div><dt>ตำแหน่ง</dt><dd>{employee.jobTitle || 'ไม่ระบุ'}</dd></div></dl>}{tab !== 'overview' && <div className="personnel-drawer-empty"><span>◌</span><b>ยังไม่มีข้อมูลส่วนนี้</b><small>แสดงเฉพาะข้อมูลที่บัญชีปัจจุบันได้รับอนุญาต</small></div>}</section><footer className="personnel-drawer-actions"><button type="button" className="small-action" onClick={onClose}>ปิด</button>{canManage && <button type="button" className="btn-primary compact" onClick={onEdit}>แก้ไขข้อมูล</button>}</footer></aside></div>;
}
