import type { AuditFilters } from './audit-types';

type Props = { pageSize: number; onPageSize(value: number): void; filters: AuditFilters; onFiltersChange(filters: AuditFilters): void; onClear(): void };

const modules = ['', 'Employee', 'EmployeeLifecycleEvent', 'EmployeeLicense', 'EmployeeReferencePhoto', 'EmployeeLicenseDocument', 'LeaveRequest', 'LeaveQuota', 'ShiftAssignment', 'ShiftType', 'ScheduleApproval', 'SchedulingRule', 'User', 'UserCredential', 'SystemSetting'];
const actions = ['', 'CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT_ALL'];

export function AuditToolbar({ pageSize, onPageSize, filters, onFiltersChange, onClear }: Props) {
  const change = (field: keyof AuditFilters, value: string) => onFiltersChange({ ...filters, [field]: value });
  return <section className="audit-toolbar data-toolbar-panel data-toolbar data-toolbar--filters" aria-label="ตัวกรองบันทึกการใช้งานระบบ"><label className={filters.dateFrom ? 'is-filtered' : ''}><span>ตั้งแต่วันที่</span><input type="date" aria-label="ตั้งแต่วันที่" value={filters.dateFrom} onChange={(event) => change('dateFrom', event.target.value)} /></label><label className={filters.dateTo ? 'is-filtered' : ''}><span>ถึงวันที่</span><input type="date" aria-label="ถึงวันที่" value={filters.dateTo} onChange={(event) => change('dateTo', event.target.value)} /></label><label className={`audit-actor-filter ${filters.actor ? 'is-filtered' : ''}`}><span>ผู้ใช้งาน</span><input aria-label="กรองตามผู้ใช้งาน" value={filters.actor} onChange={(event) => change('actor', event.target.value)} placeholder="ชื่อผู้ดำเนินการ" /></label><label className={filters.entityType ? 'is-filtered' : ''}><span>Module</span><select aria-label="กรองตาม Module" value={filters.entityType} onChange={(event) => change('entityType', event.target.value)}>{modules.map((module) => <option key={module || 'all'} value={module}>{module || 'ทุก Module'}</option>)}</select></label><label className={filters.action ? 'is-filtered' : ''}><span>Action</span><select aria-label="กรองตาม Action" value={filters.action} onChange={(event) => change('action', event.target.value)}>{actions.map((action) => <option key={action || 'all'} value={action}>{action || 'ทุก Action'}</option>)}</select></label><label className={filters.category !== 'default' ? 'is-filtered' : ''}><span>ประเภทเหตุการณ์</span><select aria-label="กรองประเภทเหตุการณ์" value={filters.category} onChange={(event) => change('category', event.target.value)}><option value="default">ธุรกิจและความปลอดภัย</option><option value="technical">Technical / System</option><option value="all">ทั้งหมด</option></select></label><label className={`audit-search ${filters.search ? 'is-filtered' : ''}`}><span>ค้นหา</span><input aria-label="ค้นหา Audit Log" value={filters.search} onChange={(event) => change('search', event.target.value)} placeholder="Module, Action หรือรหัสรายการ" /></label><label className="audit-page-size"><span>ต่อหน้า</span><select aria-label="จำนวนรายการต่อหน้า" value={pageSize} onChange={(event) => onPageSize(Number(event.target.value))}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label><button type="button" className="btn-neutral small-action audit-clear-filters data-clear-filters" onClick={onClear}>ล้างตัวกรอง</button></section>;
}
