import type { AuditEvent } from './audit-types';
import { actionLabel, entityLabel, eventLabel, formatAuditTime, metadataSummary, moduleLabel, safe } from './audit-utils';

type Props = { rows: AuditEvent[]; selected?: AuditEvent; onSelect(row: AuditEvent): void; loading: boolean; hasActiveFilters: boolean };

export function AuditTable({ rows, selected, onSelect, loading, hasActiveFilters }: Props) {
  return <div className="audit-table-card"><div className="audit-table-scroll"><table className="audit-table"><thead><tr><th scope="col">วันและเวลา</th><th scope="col">ผู้ดำเนินการ</th><th scope="col">Module</th><th scope="col">การดำเนินการ</th><th scope="col">ข้อมูลเป้าหมาย</th><th scope="col">รายละเอียด</th></tr></thead><tbody>{loading ? Array.from({ length: 5 }, (_, index) => <tr key={`skeleton-${index}`} className="audit-skeleton-row"><td colSpan={6}><span /></td></tr>) : rows.length ? rows.map((row, index) => <tr key={safe(row.id, `event-${index}`)} className={selected === row ? 'is-selected' : ''} tabIndex={0} onClick={() => onSelect(row)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(row); } }}><td data-label="วันและเวลา">{formatAuditTime(row.createdAt)}</td><td data-label="ผู้ดำเนินการ"><strong>{safe(row.actor?.displayName, 'Unknown / Deleted User')}</strong><small>{safe(row.actor?.role, 'ไม่ระบุบทบาท')}</small></td><td data-label="Module"><span className="audit-module-badge">{moduleLabel(row.module)}</span></td><td data-label="การดำเนินการ"><span className="audit-action-badge">{actionLabel(row.action)}</span><small>{eventLabel(row)}</small></td><td data-label="ข้อมูลเป้าหมาย"><strong>{entityLabel(row.entityType)}</strong><small className="audit-entity-id">{safe(row.entityId)}</small></td><td data-label="รายละเอียด"><span className="audit-row-summary">{metadataSummary(row.metadata)}</span><button type="button" className="audit-preview-link" onClick={(event) => { event.stopPropagation(); onSelect(row); }}>ดูรายละเอียด</button></td></tr>) : <tr><td colSpan={6} className="audit-no-rows"><span aria-hidden="true">⌁</span><strong>ไม่พบรายการ Audit Log ตามเงื่อนไขที่เลือก</strong><p>{hasActiveFilters ? 'ลองเปลี่ยนตัวกรองหรือขยายช่วงวันที่' : 'ยังไม่มีบันทึกที่แสดงในมุมมองนี้'}</p></td></tr>}</tbody></table></div></div>;
}

export type { AuditEvent } from './audit-types';
