const DISPLAY_TIME_ZONE = 'Asia/Bangkok';
const DATE_ONLY_PATTERN = /^(\d{4})-(\d{2})-(\d{2})$/;
type DateFormatOptions = Intl.DateTimeFormatOptions;
function parseDate(value: unknown): Date | null { if (value instanceof Date) return Number.isNaN(value.getTime()) ? null : new Date(value.getTime()); if (value === null || value === undefined || String(value).trim() === '') return null; const text = String(value).trim(); const dateOnly = DATE_ONLY_PATTERN.exec(text); if (dateOnly && (Number(dateOnly[1]) < 1900 || Number(dateOnly[1]) > 2200)) return null; const parsed = dateOnly ? new Date(`${dateOnly[1]}-${dateOnly[2]}-${dateOnly[3]}T00:00:00Z`) : new Date(text); return Number.isNaN(parsed.getTime()) ? null : parsed; }
function buddhistFormatter(options: DateFormatOptions) { return new Intl.DateTimeFormat('th-TH-u-ca-buddhist', options); }
export function formatThaiDate(value: unknown, options: DateFormatOptions = {}): string { const parsed = parseDate(value); return parsed ? buddhistFormatter({ day: 'numeric', month: 'long', year: 'numeric', timeZone: DISPLAY_TIME_ZONE, ...options }).format(parsed) : '-'; }
export function formatThaiDateTime(value: unknown): string { const parsed = parseDate(value); if (!parsed) return '-'; const datePart = buddhistFormatter({ day: 'numeric', month: 'long', year: 'numeric', timeZone: DISPLAY_TIME_ZONE }).format(parsed); const timePart = new Intl.DateTimeFormat('th-TH', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: DISPLAY_TIME_ZONE }).format(parsed); return `${datePart} เวลา ${timePart} น.`; }
export function formatThaiMonthYear(value: unknown): string { const parsed = parseDate(value); return parsed ? buddhistFormatter({ month: 'long', year: 'numeric', timeZone: DISPLAY_TIME_ZONE }).format(parsed) : '-'; }
export function formatBuddhistYear(year: number): string { return Number.isInteger(year) && year >= 1900 && year <= 2200 ? String(year + 543) : '-'; }
export function parseBuddhistYearInput(value: string | number): number | null { const year = Number(String(value).trim()); if (!Number.isInteger(year)) return null; if (year >= 2400 && year <= 2800) return year - 543; if (year >= 1900 && year <= 2200) return year; return null; }
export function toIsoDate(value: unknown): string { if (value === null || value === undefined || String(value).trim() === '') return ''; const text = String(value).trim(); if (DATE_ONLY_PATTERN.test(text)) return text; const parsed = parseDate(value); return parsed ? parsed.toISOString().slice(0, 10) : ''; }
